#!/bin/sh -e

case `uname -s` in
  *Darwin*) _PFX_="/usr/local"; CORES=`sysctl -n hw.ncpu` ;;
  *) _PFX_="/usr"; CORES=`nproc` ;;
esac

mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$_PFX_" ..

cmake --build . \
  --target fastfetch \
  --target flashfetch \
  -j"${CORES}"

make DESTDIR="$1" install
